/* ////////////////////////////////////////////////////////////////////////
Nom de la procedure stockee : SP_ATHENEO_LISTER_DEMANDES
No Version : 001
Description : Liste toutes les demandes avec filtres optionnels
//////////////////////////////////////////////////////////////////////// */

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SP_ATHENEO_LISTER_DEMANDES]') AND is_ms_shipped = 0 AND [type] IN ('P'))
DROP PROCEDURE [SP_ATHENEO_LISTER_DEMANDES]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE SP_ATHENEO_LISTER_DEMANDES(
    IN STATUT VARCHAR(20),
    IN PRIORITE VARCHAR(20),
    IN TYPE VARCHAR(50),
    IN ID_INTERLOCUTEUR BIGINT,
    IN LIMITE INT
)
LANGUAGE SQL
READS SQL DATA
AS $$
    SELECT
        ID AS DEMANDE_ID,
        REFERENCE,
        ID_INTERLOCUTEUR,
        EMAIL_CONTACT,
        CONTACT_NOM,
        TITRE,
        DESCRIPTION,
        STATUT,
        PRIORITE,
        TYPE,
        SOURCE,
        DATE_CREATION
    FROM DEMANDE
    WHERE (STATUT IS NULL OR DEMANDE.STATUT = STATUT)
      AND (PRIORITE IS NULL OR DEMANDE.PRIORITE = PRIORITE)
      AND (TYPE IS NULL OR DEMANDE.TYPE = TYPE)
      AND (ID_INTERLOCUTEUR IS NULL OR DEMANDE.ID_INTERLOCUTEUR = ID_INTERLOCUTEUR)
    ORDER BY DATE_CREATION DESC
    LIMIT LIMITE;
$$;